name: build-workflow
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir src
      - run: sudo make
      - run: ls
      - run: ls src
      - run: ls src/docker
