name: build-workflow
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
        PWD: $HOME
    steps:
      - uses: actions/checkout@v2
      - run: export PWD=${pwd}
      - run: mkdir src
      - run: sudo make
      - run: ls
      - run: ls src
      - run: ls src/docker
    #   - run: cp .env.example .env
    #   - name: Cache composer vendor
    #     uses: actions/cache@v1
    #     with:
    #       path: vendor
    #       key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
    #   - run: composer install
    #   - name: Cache node_modules
    #     uses: actions/cache@v1
    #     with:
    #       path: node_modules
    #       key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    #   - run: yarn
    #   - run: yarn prod
    #   - run: php artisan key:generate
    #   - run: vendor/bin/phpunit
    #   - run: chromedriver --whitelisted-ips > /dev/null 2>&1 &
    #   - run: php artisan serve > /dev/null 2>&1 &
    #   - run: php artisan dusk
    #   - name: Archive screenshots
    #     uses: actions/upload-artifact@v1
    #     if: always()
    #     with:
    #       name: e2e-screenshots
    #       path: tests/Browser/screenshots
    #   - name: Archive laravel log
    #     uses: actions/upload-artifact@v1
    #     if: always()
    #     with:
    #       name: laravel-log
    #       path: storage/logs
